#
# This file has been generated by tools/gen-deps.sh
#

src/s6-overlay-preinit/s6-overlay-preinit.o src/s6-overlay-preinit/s6-overlay-preinit.lo: src/s6-overlay-preinit/s6-overlay-preinit.c

s6-overlay-preinit: EXTRA_LIBS := -lskarnet
s6-overlay-preinit: src/s6-overlay-preinit/s6-overlay-preinit.o
